namespace PlaidApi.Constants
{
    public static class PlaidCategories
    {
        // Categorías de INCOME
        public const string INCOME_WAGES = "INCOME_WAGES";
        public const string INCOME_RETIREMENT_PENSION = "INCOME_RETIREMENT_PENSION";
        public const string INCOME_UNEMPLOYMENT = "INCOME_UNEMPLOYMENT";
        public const string INCOME_TAX_REFUND = "INCOME_TAX_REFUND";
        public const string INCOME_DIVIDENDS = "INCOME_DIVIDENDS";
        public const string INCOME_INTEREST_EARNED = "INCOME_INTEREST_EARNED";
        public const string INCOME_OTHER_INCOME = "INCOME_OTHER_INCOME";

        // Categorías de TRANSFER_IN
        public const string TRANSFER_IN_ACCOUNT_TRANSFER = "TRANSFER_IN_ACCOUNT_TRANSFER";
        public const string TRANSFER_IN_CASH_ADVANCES_AND_LOANS = "TRANSFER_IN_CASH_ADVANCES_AND_LOANS";
        public const string TRANSFER_IN_DEPOSIT = "TRANSFER_IN_DEPOSIT";
        public const string TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS = "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS";
        public const string TRANSFER_IN_SAVINGS = "TRANSFER_IN_SAVINGS";
        public const string TRANSFER_IN_OTHER_TRANSFER_IN = "TRANSFER_IN_OTHER_TRANSFER_IN";

        // Categorías de TRANSFER_OUT
        public const string TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS = "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS";
        public const string TRANSFER_OUT_SAVINGS = "TRANSFER_OUT_SAVINGS";
        public const string TRANSFER_OUT_WITHDRAWAL = "TRANSFER_OUT_WITHDRAWAL";
        public const string TRANSFER_OUT_ACCOUNT_TRANSFER = "TRANSFER_OUT_ACCOUNT_TRANSFER";
        public const string TRANSFER_OUT_OTHER_TRANSFER_OUT = "TRANSFER_OUT_OTHER_TRANSFER_OUT";

        // Categorías de LOAN_PAYMENTS
        public const string LOAN_PAYMENTS_CAR_PAYMENT = "LOAN_PAYMENTS_CAR_PAYMENT";
        public const string LOAN_PAYMENTS_CREDIT_CARD_PAYMENT = "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT";
        public const string LOAN_PAYMENTS_MORTGAGE_PAYMENT = "LOAN_PAYMENTS_MORTGAGE_PAYMENT";
        public const string LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT = "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT";
        public const string LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT = "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT";
        public const string LOAN_PAYMENTS_OTHER_PAYMENT = "LOAN_PAYMENTS_OTHER_PAYMENT";

        // Categorías de ENTERTAINMENT
        public const string ENTERTAINMENT_CASINOS_AND_GAMBLING = "ENTERTAINMENT_CASINOS_AND_GAMBLING";
        public const string ENTERTAINMENT_MUSIC_AND_AUDIO = "ENTERTAINMENT_MUSIC_AND_AUDIO";
        public const string ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS = "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS";
        public const string ENTERTAINMENT_TV_AND_MOVIES = "ENTERTAINMENT_TV_AND_MOVIES";
        public const string ENTERTAINMENT_VIDEO_GAMES = "ENTERTAINMENT_VIDEO_GAMES";
        public const string ENTERTAINMENT_OTHER_ENTERTAINMENT = "ENTERTAINMENT_OTHER_ENTERTAINMENT";

        // Categorías de FOOD_AND_DRINK
        public const string FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR = "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR";
        public const string FOOD_AND_DRINK_COFFEE = "FOOD_AND_DRINK_COFFEE";
        public const string FOOD_AND_DRINK_FAST_FOOD = "FOOD_AND_DRINK_FAST_FOOD";
        public const string FOOD_AND_DRINK_GROCERIES = "FOOD_AND_DRINK_GROCERIES";
        public const string FOOD_AND_DRINK_RESTAURANT = "FOOD_AND_DRINK_RESTAURANT";
        public const string FOOD_AND_DRINK_VENDING_MACHINES = "FOOD_AND_DRINK_VENDING_MACHINES";
        public const string FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK = "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK";

        // Categorías de GENERAL_SERVICES
        public const string GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING = "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING";
        public const string GENERAL_SERVICES_AUTOMOTIVE = "GENERAL_SERVICES_AUTOMOTIVE";
        public const string GENERAL_SERVICES_CHILDCARE = "GENERAL_SERVICES_CHILDCARE";
        public const string GENERAL_SERVICES_CONSULTING_AND_LEGAL = "GENERAL_SERVICES_CONSULTING_AND_LEGAL";
        public const string GENERAL_SERVICES_EDUCATION = "GENERAL_SERVICES_EDUCATION";
        public const string GENERAL_SERVICES_INSURANCE = "GENERAL_SERVICES_INSURANCE";
        public const string GENERAL_SERVICES_POSTAGE_AND_SHIPPING = "GENERAL_SERVICES_POSTAGE_AND_SHIPPING";
        public const string GENERAL_SERVICES_STORAGE = "GENERAL_SERVICES_STORAGE";
        public const string GENERAL_SERVICES_OTHER_GENERAL_SERVICES = "GENERAL_SERVICES_OTHER_GENERAL_SERVICES";

        // Categorías de GENERAL_MERCHANDISE
        public const string GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS = "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS";
        public const string GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES = "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES";
        public const string GENERAL_MERCHANDISE_CONVENIENCE_STORES = "GENERAL_MERCHANDISE_CONVENIENCE_STORES";
        public const string GENERAL_MERCHANDISE_DEPARTMENT_STORES = "GENERAL_MERCHANDISE_DEPARTMENT_STORES";
        public const string GENERAL_MERCHANDISE_DISCOUNT_STORES = "GENERAL_MERCHANDISE_DISCOUNT_STORES";
        public const string GENERAL_MERCHANDISE_ELECTRONICS = "GENERAL_MERCHANDISE_ELECTRONICS";
        public const string GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES = "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES";
        public const string GENERAL_MERCHANDISE_OFFICE_SUPPLIES = "GENERAL_MERCHANDISE_OFFICE_SUPPLIES";
        public const string GENERAL_MERCHANDISE_ONLINE_MARKETPLACES = "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES";
        public const string GENERAL_MERCHANDISE_PET_SUPPLIES = "GENERAL_MERCHANDISE_PET_SUPPLIES";
        public const string GENERAL_MERCHANDISE_SPORTING_GOODS = "GENERAL_MERCHANDISE_SPORTING_GOODS";
        public const string GENERAL_MERCHANDISE_SUPERSTORES = "GENERAL_MERCHANDISE_SUPERSTORES";
        public const string GENERAL_MERCHANDISE_TOBACCO_AND_VAPE = "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE";
        public const string GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE = "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE";

        // Categorías de HOME_IMPROVEMENT
        public const string HOME_IMPROVEMENT_FURNITURE = "HOME_IMPROVEMENT_FURNITURE";
        public const string HOME_IMPROVEMENT_HARDWARE = "HOME_IMPROVEMENT_HARDWARE";
        public const string HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE = "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE";
        public const string HOME_IMPROVEMENT_SECURITY = "HOME_IMPROVEMENT_SECURITY";
        public const string HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT = "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT";

        // Categorías de MEDICAL
        public const string MEDICAL_DENTAL_CARE = "MEDICAL_DENTAL_CARE";
        public const string MEDICAL_EYE_CARE = "MEDICAL_EYE_CARE";
        public const string MEDICAL_NURSING_CARE = "MEDICAL_NURSING_CARE";
        public const string MEDICAL_PHARMACIES_AND_SUPPLEMENTS = "MEDICAL_PHARMACIES_AND_SUPPLEMENTS";
        public const string MEDICAL_PRIMARY_CARE = "MEDICAL_PRIMARY_CARE";
        public const string MEDICAL_VETERINARY_SERVICES = "MEDICAL_VETERINARY_SERVICES";
        public const string MEDICAL_OTHER_MEDICAL = "MEDICAL_OTHER_MEDICAL";

        // Categorías de PERSONAL_CARE
        public const string PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS = "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS";
        public const string PERSONAL_CARE_HAIR_AND_BEAUTY = "PERSONAL_CARE_HAIR_AND_BEAUTY";
        public const string PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING = "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING";
        public const string PERSONAL_CARE_OTHER_PERSONAL_CARE = "PERSONAL_CARE_OTHER_PERSONAL_CARE";

        // Categorías de GOVERNMENT_AND_NON_PROFIT
        public const string GOVERNMENT_AND_NON_PROFIT_DONATIONS = "GOVERNMENT_AND_NON_PROFIT_DONATIONS";
        public const string GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES = "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES";
        public const string GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT = "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT";
        public const string GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT = "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT";

        // Categorías de TRANSPORTATION
        public const string TRANSPORTATION_BIKES_AND_SCOOTERS = "TRANSPORTATION_BIKES_AND_SCOOTERS";
        public const string TRANSPORTATION_GAS = "TRANSPORTATION_GAS";
        public const string TRANSPORTATION_PARKING = "TRANSPORTATION_PARKING";
        public const string TRANSPORTATION_PUBLIC_TRANSIT = "TRANSPORTATION_PUBLIC_TRANSIT";
        public const string TRANSPORTATION_TAXIS_AND_RIDE_SHARES = "TRANSPORTATION_TAXIS_AND_RIDE_SHARES";
        public const string TRANSPORTATION_TOLLS = "TRANSPORTATION_TOLLS";
        public const string TRANSPORTATION_OTHER_TRANSPORTATION = "TRANSPORTATION_OTHER_TRANSPORTATION";

        // Categorías de TRAVEL
        public const string TRAVEL_FLIGHTS = "TRAVEL_FLIGHTS";
        public const string TRAVEL_LODGING = "TRAVEL_LODGING";
        public const string TRAVEL_RENTAL_CARS = "TRAVEL_RENTAL_CARS";
        public const string TRAVEL_OTHER_TRAVEL = "TRAVEL_OTHER_TRAVEL";

        // Categorías de BANK_FEES
        public const string BANK_FEES_ATM_FEES = "BANK_FEES_ATM_FEES";
        public const string BANK_FEES_FOREIGN_TRANSACTION_FEES = "BANK_FEES_FOREIGN_TRANSACTION_FEES";
        public const string BANK_FEES_INSUFFICIENT_FUNDS = "BANK_FEES_INSUFFICIENT_FUNDS";
        public const string BANK_FEES_INTEREST_CHARGE = "BANK_FEES_INTEREST_CHARGE";
        public const string BANK_FEES_OVERDRAFT_FEES = "BANK_FEES_OVERDRAFT_FEES";
        public const string BANK_FEES_OTHER_BANK_FEES = "BANK_FEES_OTHER_BANK_FEES";

        // Categorías de RENT_AND_UTILITIES
        public const string RENT_AND_UTILITIES_GAS_AND_ELECTRICITY = "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY";
        public const string RENT_AND_UTILITIES_INTERNET_AND_CABLE = "RENT_AND_UTILITIES_INTERNET_AND_CABLE";
        public const string RENT_AND_UTILITIES_RENT = "RENT_AND_UTILITIES_RENT";
        public const string RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT = "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT";
        public const string RENT_AND_UTILITIES_TELEPHONE = "RENT_AND_UTILITIES_TELEPHONE";
        public const string RENT_AND_UTILITIES_WATER = "RENT_AND_UTILITIES_WATER";
        public const string RENT_AND_UTILITIES_OTHER_UTILITIES = "RENT_AND_UTILITIES_OTHER_UTILITIES";

        // Primary categories
        public const string INCOME = "INCOME";
        public const string TRANSFER_IN = "TRANSFER_IN";
        public const string TRANSFER_OUT = "TRANSFER_OUT";
        public const string LOAN_PAYMENTS = "LOAN_PAYMENTS";
        public const string BANK_FEES = "BANK_FEES";
        public const string ENTERTAINMENT = "ENTERTAINMENT";
        public const string FOOD_AND_DRINK = "FOOD_AND_DRINK";
        public const string GENERAL_MERCHANDISE = "GENERAL_MERCHANDISE";
        public const string HOME_IMPROVEMENT = "HOME_IMPROVEMENT";
        public const string MEDICAL = "MEDICAL";
        public const string PERSONAL_CARE = "PERSONAL_CARE";
        public const string GENERAL_SERVICES = "GENERAL_SERVICES";
        public const string GOVERNMENT_AND_NON_PROFIT = "GOVERNMENT_AND_NON_PROFIT";
        public const string TRAVEL = "TRAVEL";
        public const string TRANSPORTATION = "TRANSPORTATION";
        public const string RENT_AND_UTILITIES = "RENT_AND_UTILITIES";

    }
}
